# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/tanveer/risc/Pipelined/vivado/risc_pl.cache/wt [current_project]
set_property parent.project_path /home/tanveer/risc/Pipelined/vivado/risc_pl.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths /home/tanveer/PYNQ/YOLO_Tiny/code/test/ip_example [current_project]
update_ip_catalog
set_property ip_output_repo /home/tanveer/risc/Pipelined/vivado/risc_pl.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/tanveer/risc/Pipelined/arth_logic_unit.v
  /home/tanveer/risc/Pipelined/control_unit.v
  /home/tanveer/risc/Pipelined/data_forwarding_unit.v
  /home/tanveer/risc/Pipelined/datapath.v
  /home/tanveer/risc/Pipelined/ex_wb_pl_reg.v
  /home/tanveer/risc/Pipelined/exec_unit.v
  /home/tanveer/risc/Pipelined/id_ex_pl_reg.v
  /home/tanveer/risc/Pipelined/if_id_pl_reg.v
  /home/tanveer/risc/Pipelined/inst_decode_unit.v
  /home/tanveer/risc/Pipelined/inst_fetch_unit.v
  /home/tanveer/risc/Pipelined/regfile.v
  /home/tanveer/risc/Pipelined/risc_core.v
  /home/tanveer/risc/Pipelined/vivado/risc_pl.srcs/sources_1/new/risc_soc_synth.v
}
read_ip -quiet /home/tanveer/risc/Pipelined/vivado/risc_pl.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all /home/tanveer/risc/Pipelined/vivado/risc_pl.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/tanveer/risc/Pipelined/vivado/risc_pl.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files /home/tanveer/risc/Pipelined/vivado/risc_pl.srcs/constrs_1/new/const.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top risc_soc_synth -part xc7z020clg400-1 -directive AlternateRoutability -no_lc -shreg_min_size 10


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef risc_soc_synth.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file risc_soc_synth_utilization_synth.rpt -pb risc_soc_synth_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
